name: EKS Deployments

on:
  push:
    branches:
      - main
    paths:
      - "nginx-deployment.yaml"
      - "nginx-service.yaml"
      - "ingress.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region ap-northeast-2 --name eks-vpc-cluster
          kubectl apply -f nginx-deployment.yaml
          kubectl apply -f nginx-service.yaml
          kubectl apply -f ingress.yaml
